name: LHC_QML
dependencies:
  - ipython=8.13
  - matplotlib=3.7
  - pandas=2.0
  - pip=23.1
  - python=3.11
  - scikit-learn=1.2
  - seaborn=0.12
  - uproot=5.0
  - pylatexenc=2.10
  - pip:
      - numpy==1.23.5
      - dill==0.3.6
      - qiskit==0.43
      - qiskit-machine-learning==0.6.1
      - symengine==0.9.2
